### ISSUE TITLE
Different Arm/Shank lengths?

### ISSUE THREAD

**Issue by odwdinc** [ftobler/robotArm#1]
I am trying to use your code in other project.
you have a set Arm/Shank of 120mm and a height of 122mm, I wish to use with 210mm, 230mm, height 126mm,

I see a 2 points you use 120, and none with 122??
robotArm
67:  interpolator.setInterpolation(0,120,120,0, 0,120,120,0);
robotGeometry.cpp
47:   high = acos((rside * 0.5) / 120.0) * 2.0;  //120mm shank length
can you better explain these lines? 

Thanks

**Comment by ftobler** [comment]
Can you reference from where you have that 122mm? It is definitely 120mm. Every other reference is wrong, I can't find it.
On Thingiverse you can find a CAD drawing with the most important measurements. You can also find a hand written explanation of the Inverse Kinematics.

`interpolator.setInterpolation(...)` will move the arm from x1,y2,z1 to x2,y2,z3. Doing it while steppers off results in no movements but updating of internal variables.

`high = acos((rside * 0.5) / 120.0) * 2.0;` is part of the Inverse Kinematics. It creates an equilateral triangle with the lower and higher shank. So they both have to be of the same length for that to work. I won't go into the formulas here, they are explained on thingiverse on the document "robotGeometry.pdf". If you want to use a different length you have to develop the formulas for that.

**Comment by odwdinc** [comment]
The height of 122mm is form your https://www.thingiverse.com/thing:1718984  cad drawing,
https://thingiverse-production-new.s3.amazonaws.com/assets/ab/ea/1e/45/9a/doc3.png

shows 122m form the base to the first joint the other 2 joints are 120mm,

ok thanks for the info all fit my formulas then.

**Comment by ftobler** [comment]
Thanks for the height reference. I did not look at the base at all. The zero point is at the height of the main center axis. So it is simple to subtract the height from the Z-direction if needed.
